### PR TITLE
Correct some of the grammar.

### PR DESCRIPTION
**Pull request by shlomif**
I found one problem with "it's" vs. "its" and grepped for other "it's"es
and found other problems, which I also corrected.

### CODE REVIEW

**Comment by squatto** [comment]
Could you check against https://github.com/denysdovhan/wtfjs/pull/72 to see if any are different?

**Comment by shlomif** [comment]
Hi Scott,

On Tue, 24 Oct 2017 08:57:07 -0700
Scott Carpenter <notifications@github.com> wrote:

> Could you check against https://github.com/denysdovhan/wtfjs/pull/72 to see
> if any are different?
> 

some of my corrections are indeed different to the ones in that pull-req. If
you want, you can merge it first and I will rebase my changes based on them.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
https://is.gd/MQHVF3 - The Atom Text Editors edits a 2,000,001B file

The one and only, 100% original, real, actual, and unmatched, Slimy Fish™!

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by squatto** [comment]
Perfect, thanks for checking that! We'll wait for @denysdovhan to merge mine and then go from there.

**Comment by denysdovhan** [comment]
Seems like after merging #72 some conflicts occur. @shlomif @squatto can you resolve these problems?

**Comment by shlomif** [comment]
@denysdovhan : sure, I'll get to it.

**Comment by shlomif** [comment]
@denysdovhan @squatto : rebased. Feel free to merge now.

**Comment by denysdovhan** [comment]
Thanks for contributing!
Published as `v1.3.1`!

**Comment by shlomif** [comment]
On Mon, 30 Oct 2017 05:54:20 -0700
Denys Dovhan <notifications@github.com> wrote:

> Thanks for contributing!
> Published as `v1.3.1`!
> 

you are welcome! Thanks for merging my changes.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Text Editors and IDEs - http://shlom.in/IDEs

The KGB used to torture their victims by having them look at scrolling XSLT
code.
    — http://www.shlomifish.org/humour/bits/facts/XSLT/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Pull request merged**
