### PR TITLE
Hindi translation

### PR DESCRIPTION
**Pull request by hidaytrahman**

### CODE REVIEW

**Comment by hidaytrahman** [comment]
Could you please review and merge or share a suggestion if required

**Review by denysdovhan — CHANGES_REQUESTED** [review]
Add a link to your translation in the main README.md file.
Also, find someone to review your translation.
Thanks!

**Comment by hidaytrahman** [comment]
did the changes in readme.md 

He can review for hindi @amarjitCloud

**Review by hidaytrahman — COMMENTED** [review]
changes are done for Hindi language

**Comment by denysdovhan** [comment]
I still don't see any approvals of your translation. Please, ask someone to review.

**Comment by denysdovhan** [comment]
@amarjitCloud is there any chance you take a look at this?

**Comment by hidaytrahman** [comment]
I guess he is super busy. Can I add someone else for review?

**Comment by denysdovhan** [comment]
@hidaytrahman sure. Just find anyone who can read and approve your translation.

**Comment by hidaytrahman** [comment]
Thank you @denysdovhan.

Hi @ayatrahmani  could you please review my translation?

**Comment by ayatrahmani** [comment]
Hi @hidaytrahman 

Looks good.

**Review by denysdovhan — APPROVED** [review]

**Comment by denysdovhan** [comment]
Thanks for contributing!

**Pull request merged**
