### PR TITLE
Sinhala translation

### PR DESCRIPTION
**Pull request by pavinduLakshan**
referencing #93

### CODE REVIEW

**Review by denysdovhan — CHANGES_REQUESTED** [review]
You should include a link to your translation in the main README.md file.

Also, find someone to check and approve your translation. Thanks!

**Comment by pavinduLakshan** [comment]
@denysdovhan, First off, thanks for having a look at my PR, but I have a little thing to clarify.

> Also, find someone to check and approve your translation. Thanks!

 can you kindly explain what should I exactly do?

**Comment by denysdovhan** [comment]
@pavinduLakshan find someone who speaks your language to check and approve your translation. I need to make sure your translation is well and readable.

**Comment by denysdovhan** [comment]
@pavinduLakshan Any update? Did you find someone to review it?

**Comment by Udith-Gayan** [comment]
@denysdovhan Hi, As per @pavinduLakshan's request, I started reviewing his changes, as a native speaker of Sinhalese. I need some time to review it. Once my review is over, I'll give my comment. Thank you

**Comment by Udith-Gayan** [comment]
Hi @denysdovhan,   I reviewed the file edited by @pavinduLakshan . The translation is in a quite good state and well readable.  I didn't even see any typo and I felt that he had done the translation very carefully. 
Thank you.

**Comment by denysdovhan** [comment]
Thanks for contributing!

**Pull request merged**
