### PR TITLE
 Add "resolve() won't return Promise instance" 

### PR DESCRIPTION
**Pull request by libook**
## resolve() won't return Promise instance

```javascript
const theObject = {
  "a": 7,
};
const thePromise = new Promise((resolve, reject) => {
  resolve(theObject);
}); // -> Promise instance object

thePromise.then(value => {
  console.log(value === theObject); // -> true
  console.log(value); // -> { a: 7 }
})
```

The `value` which is resolved from `thePromise` is exactly `theObject`.

How about input another `Promise` into the `resolve` function?

```javascript
const theObject = new Promise((resolve, reject) => {
  resolve(7);
}); // -> Promise instance object
const thePromise = new Promise((resolve, reject) => {
  resolve(theObject);
}); // -> Promise instance object

thePromise.then(value => {
  console.log(value === theObject); // -> false
  console.log(value); // -> 7
})
```

### 💡 Explanation:

> If the value (which is inputted into resolve function) is a thenable (i.e. has a "then" method), the returned promise will "follow" that thenable, adopting its eventual state; otherwise the returned promise will be fulfilled with the value.

&ndash; [Promise.resolve() on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)

 The specification is [ECMAScript 25.6.1.3.2 Promise Resolve Functions](https://tc39.es/ecma262/#sec-promise-resolve-functions). But it is not quite human-friendly.

### CODE REVIEW

**Review by denysdovhan — CHANGES_REQUESTED** [review]
Please, resolve the conflict. Thank you for your contribution!

**Comment by libook** [comment]
@denysdovhan 
Finally.
Conflicts are resolved. Please review.

**Comment by libook** [comment]
Also updated information from MDN.

**Review by denysdovhan — APPROVED** [review]

**Comment by denysdovhan** [comment]
Thank you!

**Pull request merged**
